project_id = "yulegybknvtanqkipsbj"

[functions.send-whatsapp]
verify_jwt = true

[functions.check-loan-reminders]
verify_jwt = false

[functions.check-overdue-loans]
verify_jwt = false

[functions.daily-summary]
verify_jwt = false

[functions.weekly-summary]
verify_jwt = false

[functions.check-bills-due]
verify_jwt = false

[functions.check-contract-reminders]
verify_jwt = false

[functions.check-overdue-contracts]
verify_jwt = false

[functions.cakto-webhook]
verify_jwt = false

[functions.check-vehicle-reminders]
verify_jwt = false

[functions.check-overdue-vehicles]
verify_jwt = false

[functions.broadcast-whatsapp]
verify_jwt = false

[functions.create-trial-user]
verify_jwt = false

[functions.check-expired-subscriptions]
verify_jwt = false

[functions.list-trial-users]
verify_jwt = false
